# python -m pip install -e .

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ipa-clutch-batch"
dynamic = ["version"]
description = "Batch install IPA files and run Clutch over an SSH tunnel."
requires-python = ">=3.10"
dependencies = [
    "paramiko==3.5.1",
]

[project.scripts]
# configure command line entry point
# just type ipa-clutch-batch in console
ipa-clutch-batch = "ipa_clutch_batch.main:main"

[tool.setuptools]
# all source code is under src folder
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
# find all python packages under src folder
where = ["src"]

[tool.setuptools.dynamic]
# find variable __version__ in ipa_clutch_batch.version.__version__
version = {attr = "ipa_clutch_batch.version.__version__"}

[tool.pytest.ini_options]
addopts = "-v --tb=short --show-capture=no"
testpaths = ["tests"]
pythonpath = ["src"]
markers = [
    "pytest: run all tests (pytest)",
    "unit: unit tests under tests/unit (pytest --unit)",
]
